### ISSUE TITLE
Consider using v14 build tasks package iso v15 package

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#210]
https://www.nuget.org/packages/Microsoft.VisualStudio.Sdk.BuildTasks.14.0/14.0.12-pre

**Comment by hmemcpy** [comment]
Are you sure this would work? I was looking for some info on vsix3, I found your closed issue here: #161.
I just tried using `Microsoft.VisualStudio.Sdk.BuildTasks.14.0` on an empty 2017 VSIX project. After vsix roundtripping and opening it in VS2015, I was indeed able to build it, unfortunately, attempting to double-click the produced vsix (which is launched using VS2017's `vsixinstaller.exe`), produces the following error:

![image](https://cloud.githubusercontent.com/assets/601206/22063642/7dbd0526-dd88-11e6-9df3-ff5536cd2454.png)

with the following trace:

```
Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

After digging deeper into vsixinstaller.exe, it gets confused due to the pretense of `<Prerequisites>` element inside the .vsixmanifest. This element is new in vsix3, and vsixinstaller knows it's reading a vsix2 extension (because it was compiled with v14 tools), therefore it throws.

I was able to solve this issue by reading more of the decompilation: if you modify the prerequisite node to point to `Microsoft.Framework.NDP` instead, it will work in vsixinstaller 2017!
Place this in the .vsixmanifest:

  <Prerequisites>
    <Prerequisite Id="Microsoft.Framework.NDP" Version="[4.5,)" DisplayName="Microsoft .NET Framework" />
  </Prerequisites>

And now you'll truly be able to compile the extension using both v14 and v15 build tasks!

**Comment by ErikEJ** [comment]
It works fine for me (I did start from a VS 2015 project, though)
Did you add the  VsixType v3 to your csproj? (see the note on NuGet for the package)

**Comment by ErikEJ** [comment]
Also, your vsix must contain the required new json files, if not, then you are missing the VsixType setting in your csproj

**Comment by hmemcpy** [comment]
Hah, I missed that :) Yes, you're right :) The `VsixType` was the required step...
Anyway, I learned the hard way what makes v2 and v3 vsix differ as far as vsixinstaller is concerned :)

**Comment by hmemcpy** [comment]
Thanks! By the way, I had no luck doing this with Microsoft.VSSDK.BuildTools. Is `Microsoft.VisualStudio.Sdk.BuildTasks.14.0` replacing that one? Or... what is the difference between them?

**Comment by ErikEJ** [comment]
You can do it  Microsoft.VSSDK.BuildTools if you use version 15: https://www.nuget.org/packages/Microsoft.VSSDK.BuildTools/15.0.26109-RC3 (then the VsixType setting is not required) - but then you cannot debug.... (In fact I cannot debug with Microsoft.VSSDK.BuildTools  either, raised a question on Gitter)

**Comment by hmemcpy** [comment]
By the way, it's probably best to ignore my "hack" with the NDP. Trying to upload this extension to the gallery doesn't work:
![image](https://cloud.githubusercontent.com/assets/601206/22078764/dd6ecf3e-ddc1-11e6-9832-9f5d33f1a3de.png)

So the safest, and most correct way is, of course, with the nuget package!

**Comment by ErikEJ** [comment]
Thnaks, I will just go for CoreEditor for now, that already works for me!

**Comment by hmemcpy** [comment]
Awesome! Thank you for documenting your process with issues, I don't think I would have found the nuget package without it :)

**Comment by ErikEJ** [comment]
You are welcome, always happy to share!
