### ISSUE TITLE
I get error message during connection process

### ISSUE THREAD

**Issue by relbraun** [ErikEJ/SqlCeToolbox#399]
I followed the instructions how to install and connect to sqlite and I receiving an error message 
![image](https://user-images.githubusercontent.com/6196995/27378861-def17f8a-5681-11e7-9518-6362d11f2b22.png)

### Further technical details
Toolbox version: 4.7

Database engine: (SQlite)

Visual Studio 2017

**Comment by ErikEJ** [comment]
1: Did you follow the guide here? https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider 

2: Please show the result from the About dialog in the Toolbox

3: please share your app.config/web.config and packages.config files (or even better, a repro project)

**Comment by relbraun** [comment]
1. I followed that guide except the version of the sqlite-netFx46-setup-bundle-x86-2015-1.0.105.1.exe file that I didn't find the exact version and I installed newer one.
2. Sorry but where can I find the About dialog in the Toolbox
3. App.config:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
    <remove invariant="System.Data.SQLite" /><add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" /></DbProviderFactories>
  </system.data>
</configuration>`
package.config:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
    <remove invariant="System.Data.SQLite" /><add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" /></DbProviderFactories>
  </system.data>
</configuration>`

**Comment by ErikEJ** [comment]
You need to marke the config file contents as code

**Comment by relbraun** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.2" />
  </startup>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
    <remove invariant="System.Data.SQLite" /><add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" /></DbProviderFactories>
  </system.data>
</configuration>
```

**Comment by ErikEJ** [comment]
Your DbProviderFacories section does not look like in the wiki post.

And also share packages.config and About from the Toolbox as well, please

**Comment by relbraun** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.0.0" targetFramework="net452" />
  <package id="Geckofx45" version="45.0.31" targetFramework="net452" />
  <package id="System.Data.SQLite" version="1.0.105.0" targetFramework="net452" />
  <package id="System.Data.SQLite.Core" version="1.0.105.0" targetFramework="net452" />
  <package id="System.Data.SQLite.EF6" version="1.0.105.0" targetFramework="net452" />
  <package id="System.Data.SQLite.Linq" version="1.0.105.0" targetFramework="net452" />
</packages>
```
Where can I find the About from the Toolbox?

Thank u for your patience

**Comment by ErikEJ** [comment]
In the SQLite Toolbox, click the blue question mark icon - and take a screenshot

**Comment by ErikEJ** [comment]
You should install the 105.2 SQLite packages, if you have installed the 105.2 tools! https://www.nuget.org/packages/System.Data.SQLite/

**Comment by relbraun** [comment]
![image](https://user-images.githubusercontent.com/6196995/27381074-0e4d0f6c-568a-11e7-89d7-adfc5ea53796.png)

**Comment by ErikEJ** [comment]
SQLite EF6 DbProvider in GAC - NO!

So you did not install sqlite-netFx46-setup-bundle-x86-2015-1.0.105.2.exe  properly (or restart VS after install - I have added this to the wiki post)

**Comment by relbraun** [comment]
It is very odd, I have installed it now and restart the vs and it still tells me it is not installed

**Comment by ErikEJ** [comment]
Restart PC??

**Comment by relbraun** [comment]
nothing

**Comment by relbraun** [comment]
Do you have any idea why SQLite EF6 DbProvider in GAC - NO?

**Comment by ErikEJ** [comment]
Because it is not installed and registered in machine.config in C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config folder

**Comment by relbraun** [comment]
how can I do it?

**Comment by ErikEJ** [comment]
Run the installer as Admin?

**Comment by relbraun** [comment]
I did it and nothing

**Comment by ErikEJ** [comment]
I am unable to help you further, sorry, other than you trying on another PC...

**Comment by relbraun** [comment]
@ErikEJ Thank u for you goodwill and efforts.

**Comment by ErikEJ** [comment]
Did you look at the log file? C:\Users\pkrish6\AppData\Local\Temp\Installer.exe.trace.tmp31D8.log 

Please ask at system.data.sqlite

**Comment by ramkris06** [comment]
Same data in log file . No other new information. Tried installing again.

Installer.exe: #001 @ 2018.04.14T14:28:31.0876210: Assembly: "Installer, Version=1.0.108.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139"
Installer.exe: #002 @ 2018.04.14T14:28:31.0916181: LogFileName: "C:\Users\pkrish6\AppData\Local\Temp\Installer.exe.trace.tmp512E.log"
Installer.exe: #003 @ 2018.04.14T14:28:31.0916181: RegistryLogFileName: <null>
Installer.exe: #004 @ 2018.04.14T14:28:31.0926194: Directory: "C:\Dev\sqlite-4-6-binary\sqlite-netFx46-binary-x64-2015-1.0.108.0"
Installer.exe: #005 @ 2018.04.14T14:28:31.0926194: CoreFileName: "C:\Dev\sqlite-4-6-binary\sqlite-netFx46-binary-x64-2015-1.0.108.0\System.Data.SQLite.dll"
Installer.exe: #006 @ 2018.04.14T14:28:31.0926194: LinqFileName: "C:\Dev\sqlite-4-6-binary\sqlite-netFx46-binary-x64-2015-1.0.108.0\System.Data.SQLite.Linq.dll"
Installer.exe: #007 @ 2018.04.14T14:28:31.0926194: Ef6FileName: "C:\Dev\sqlite-4-6-binary\sqlite-netFx46-binary-x64-2015-1.0.108.0\System.Data.SQLite.EF6.dll"
Installer.exe: #008 @ 2018.04.14T14:28:31.0926194: DesignerFileName: "C:\Dev\sqlite-4-6-binary\sqlite-netFx46-binary-x64-2015-1.0.108.0\SQLite.Designer.dll"
Installer.exe: #009 @ 2018.04.14T14:28:31.0926194: RegistryVersion: <null>
Installer.exe: #010 @ 2018.04.14T14:28:31.0926194: ConfigVersion: <null>
Installer.exe: #011 @ 2018.04.14T14:28:31.0936185: VsVersionSuffix: <null>
Installer.exe: #012 @ 2018.04.14T14:28:31.0936185: DebugFormat: "#{0:000} @ {1}: {2}"
Installer.exe: #013 @ 2018.04.14T14:28:31.0936185: TraceFormat: "#{0:000} @ {1}: {2}"
Installer.exe: #014 @ 2018.04.14T14:28:31.0936185: InstallFlags: Default
Installer.exe: #015 @ 2018.04.14T14:28:31.0936185: ProviderFlags: Default
Installer.exe: #016 @ 2018.04.14T14:28:31.0936185: DebugPriority: Default
Installer.exe: #017 @ 2018.04.14T14:28:31.0936185: TracePriority: Default
Installer.exe: #018 @ 2018.04.14T14:28:31.0936185: PerUser: False
Installer.exe: #019 @ 2018.04.14T14:28:31.0936185: Install: True
Installer.exe: #020 @ 2018.04.14T14:28:31.0936185: Wow64: False
Installer.exe: #021 @ 2018.04.14T14:28:31.0936185: NoRuntimeVersion: False
Installer.exe: #022 @ 2018.04.14T14:28:31.0946187: NoDesktop: False
Installer.exe: #023 @ 2018.04.14T14:28:31.0946187: NoCompact: False
Installer.exe: #024 @ 2018.04.14T14:28:31.0946187: NoNetFx20: False
Installer.exe: #025 @ 2018.04.14T14:28:31.0946187: NoNetFx35: False
Installer.exe: #026 @ 2018.04.14T14:28:31.0956192: NoNetFx40: False
Installer.exe: #027 @ 2018.04.14T14:28:31.0956192: NoNetFx45: False
Installer.exe: #028 @ 2018.04.14T14:28:31.0966190: NoNetFx451: False
Installer.exe: #029 @ 2018.04.14T14:28:31.0966190: NoNetFx452: False
Installer.exe: #030 @ 2018.04.14T14:28:31.0976192: NoNetFx46: False
Installer.exe: #031 @ 2018.04.14T14:28:31.1006201: NoNetFx461: False
Installer.exe: #032 @ 2018.04.14T14:28:31.1006201: NoNetFx462: False
Installer.exe: #033 @ 2018.04.14T14:28:31.1016199: NoNetFx47: False
Installer.exe: #034 @ 2018.04.14T14:28:31.1016199: NoNetFx471: False
Installer.exe: #035 @ 2018.04.14T14:28:31.1026197: NoVs2005: False
Installer.exe: #036 @ 2018.04.14T14:28:31.1026197: NoVs2008: False
Installer.exe: #037 @ 2018.04.14T14:28:31.1026197: NoVs2010: False
Installer.exe: #038 @ 2018.04.14T14:28:31.1036199: NoVs2012: False
Installer.exe: #039 @ 2018.04.14T14:28:31.1036199: NoVs2013: False
Installer.exe: #040 @ 2018.04.14T14:28:31.1046197: NoVs2015: False
Installer.exe: #041 @ 2018.04.14T14:28:31.1046197: NoVs2017: False
Installer.exe: #042 @ 2018.04.14T14:28:31.1056195: NoTrace: False
Installer.exe: #043 @ 2018.04.14T14:28:31.1056195: NoConsole: False
Installer.exe: #044 @ 2018.04.14T14:28:31.1066194: NoLog: False
Installer.exe: #045 @ 2018.04.14T14:28:31.1066194: ThrowOnMissing: True
Installer.exe: #046 @ 2018.04.14T14:28:31.1066194: WhatIf: True
Installer.exe: #047 @ 2018.04.14T14:28:31.1076195: Debug: False
Installer.exe: #048 @ 2018.04.14T14:28:31.1076195: Verbose: False
Installer.exe: #049 @ 2018.04.14T14:28:31.1086190: Confirm: False
Installer.exe: #050 @ 2018.04.14T14:28:31.1106197: AssemblyTitle: "System.Data.SQLite Designer Installer"
Installer.exe: #051 @ 2018.04.14T14:28:31.1106197: AssemblyConfiguration: "Release"
Installer.exe: #052 @ 2018.04.14T14:28:31.1116199: IsSystemEf6AssemblyAvailable: False
Installer.exe: #053 @ 2018.04.14T14:28:31.1116199: IsSystemEf6AssemblyGlobal: False
Installer.exe: #054 @ 2018.04.14T14:28:31.1126204: IsLinqSupported: True
Installer.exe: #055 @ 2018.04.14T14:28:31.1136199: IsEf6Supported: False
Installer.exe: #056 @ 2018.04.14T14:28:31.1136199: IsEf6AssemblyGlobal: False
Installer.exe: #057 @ 2018.04.14T14:28:31.1146201: UseEf6Provider: False
Installer.exe: #058 @ 2018.04.14T14:28:31.1156220: GetCoreAssemblyName: "System.Data.SQLite, Version=1.0.108.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139"
Installer.exe: #059 @ 2018.04.14T14:28:31.1156220: GetLinqAssemblyName: "System.Data.SQLite.Linq, Version=1.0.108.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139"
Installer.exe: #060 @ 2018.04.14T14:28:31.1166193: GetEf6AssemblyName: <null>
Installer.exe: #061 @ 2018.04.14T14:28:31.1166193: GetDesignerAssemblyName: "SQLite.Designer, Version=1.0.108.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139"
Installer.exe: #062 @ 2018.04.14T14:28:31.1176213: GetInvariantName: "System.Data.SQLite"
Installer.exe: #063 @ 2018.04.14T14:28:31.1186197: GetConfigInvariantName: "System.Data.SQLite"
Installer.exe: #064 @ 2018.04.14T14:28:31.1206208: GetProviderInvariantName: "System.Data.SQLite"
Installer.exe: #065 @ 2018.04.14T14:28:31.1216199: GetFactoryTypeName: "System.Data.SQLite.SQLiteFactory"
Installer.exe: #066 @ 2018.04.14T14:28:31.1226197: GetProviderAssemblyName: "System.Data.SQLite, Version=1.0.108.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139"
Installer.exe: #067 @ 2018.04.14T14:28:31.1246204: Configuration.Process: No actual changes will be made to this system because "what-if" mode is enabled.
Installer.exe: #068 @ 2018.04.14T14:28:31.1256199: TraceOps.ShowMessage: Cannot continue, the "confirm" option is not enabled.
Installer.exe: #069 @ 2018.04.14T14:28:38.0351868: TraceOps.ShowMessage: User choice of OK.
Installer.exe: #070 @ 2018.04.14T14:28:38.0351868: Installer.Main: Failure.

**Comment by ErikEJ** [comment]
I cannot assist, suggest you ask at system.data.sqlite.org
