### ISSUE TITLE
EFPT: Use Handlebars package with reveng (optional)

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#534]
https://www.nuget.org/packages/EntityFrameworkCore.Scaffolding.Handlebars 

https://github.com/aspnet/EntityFrameworkCore/issues/4038#issuecomment-339321010 

@tonysneed

**Comment by tonysneed** [comment]
Since it's possible to have more than one extensions package, I suggest having a drop down where the developer can select a package to use to customize code gen.  For example, I'm going to add a package to generate TypeScript classes.

I've created an [issue](https://github.com/aspnet/EntityFrameworkCore/issues/10154) on the EF Core repo for specifying a NuGet package when reverse engineering classes, similar to the provider argument to dbcontext scaffold.

I've also created an [issue](https://github.com/aspnet/EntityFrameworkCore/issues/10156) on the EF Core repo to add a feature for reverse engineer options.

**Comment by ErikEJ** [comment]
Thanks, I wiil do that. The second issue you mention is already implemented in EF Core Power Tools

**Comment by tonysneed** [comment]
I actually took a close look at your implementation, but it look like you're still generating both context and entity classes but selectively adding them to the project (please correct me if I'm mistaken).  But the approach I take in my package and what I'm recommending to EF Core is to prevent generation from taking place for entities when context only is selected (and vice versa).

**Comment by ErikEJ** [comment]
Correct.

**Comment by tonysneed** [comment]
So, I think the ideal is for an option in EF Core tooling to add generation options.  We're tracking this now with issue [1836](https://github.com/aspnet/EntityFrameworkCore/issues/1836), and I'm planning on a PR to add this to EF Core.  Then your EF Core Power Tools can just use it.

**Comment by ErikEJ** [comment]
@tonysneed Yes, a few years from now ;-)

**Comment by ErikEJ** [comment]
Waiting for strongly signed package
