### ISSUE TITLE
When exporting database schema from Sql Server NVARCHAR(max) becomes NTEXT

### ISSUE THREAD

**Issue by HillMountain** [ErikEJ/SqlCeToolbox#542]
When exporting database schema from Sql Server NVARCHAR(max) becomes NTEXT. See attached screenshot.

### Steps to reproduce
Create a tablein Sql Server with a column definition NVARCHAR(MAX). Then open Sql Server Compact Toolbox in VS and connect to Sql Server. Right-click, choose Script database and Script Database Schema.

### Further technical details
Version 4.7.234.0
SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No
SQL Server Compact 3.5 DDEX provider - No
Sync Framework 2.1 SqlCe 3.5 provider - No
SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No

Database engine: SQL Server

Visual Studio or SSMS version: VS 2017 Prof. (15.3.3)

![image](https://user-images.githubusercontent.com/30545807/32211015-d995c43c-be10-11e7-81ea-5ea60b438d80.png)

**Comment by ErikEJ** [comment]
This is by design - the schema is scripted in order to be compatible with SQL Server Compact, which does not support nvarchar(MAX) data type. (This should also be indicated by the Tooltip on the menu item). If you just want plain scripting of a SQL Server database schema, use the scripting tools in SQL Server Management Studio (SSMS)
