### ISSUE TITLE
Example on Handlebars usage

### ISSUE THREAD

**Issue by statler** [ErikEJ/SqlCeToolbox#683]
Hi Erik

This is great work. So much better than the EF standard reverse engineering. I am really interested in what we can do with the Handlebars integration (specifically I am trying to achieve something like what is described in 640 with custom column names). 

I am trying to figure out how to register a helper that will CamelCase all names coming from the database. Would it be possible to put a quick example in your readme?

**Comment by OmiCron07** [comment]
I need to know too because I have to add some custom code in the method OnModelCreating.

**Comment by ErikEJ** [comment]
I have some sample code here: https://github.com/ErikEJ/SqlCeToolbox/issues/606 - not sure it helps with "OnModelCreating" - @OmiCron07 : Maybe if I added a partial method to the body of OnModelCreating?


     partial void OnModelCreatinExtension(modelBuilder);

**Comment by OmiCron07** [comment]
Could be a solution. For now, I created a new class which inherits from my DbContext and added "protected override void OnModelCreating(ModelBuilder modelBuilder)".

But my solution is not the cleanest because I have to create a third class for inheritance, in addition of the partial class of my DbContext and the refactoring of the codes using the data context.

If you add the partial method, I suppose I can implement it in my partial class of the DbContext?

**Comment by ErikEJ** [comment]
>> If you add the partial method, I suppose I can implement it in my partial class of the DbContext?

Yes, that was the idea

**Comment by ErikEJ** [comment]
Plan to fix in #695

**Comment by ErikEJ** [comment]
@OmiCron07 Fixed in latest daily build
