### ISSUE TITLE
[SQLITE] Window Functions are not enabled

### ISSUE THREAD

**Issue by davidlmorris** [ErikEJ/SqlCeToolbox#780]
The new(ish) SQLite window functions are not available (causing Syntax errors).  Specifically in my case, the use of ROW_NUMBER().  
cf https://www.sqlite.org/windowfunctions.html

I suspect that since the ServerVersion is 3.24.0 and SQLite window functions were released in 3.25.0 the issue is about the version of System.Data.SQLite used?  System.Data.SQLite was updated March 4, 2019, to use SQLite 3.27.2.

Any chance of an update?

### Further technical details
Toolbox/Power Tools version: 4.7.632.0
ErikEJ.SqlCeScripting version 3.5.2.80
Database engine: SQlite
SSMS version: 14.0.17280.0

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by jbenzshawel** [comment]
What version is this fixed in? I am using version 4.7.634.0 and the SQLite "ROW_NUMBER()" function is not supported. 

I have a View that uses a calculated row number for the id and this is breaking the tool. Error message:

ErrorCode : 11
Message   : database disk image is malformed
malformed database schema (VwProductItemCustomerPricing) - near "(": syntax error
Result    : Corrupt

Thanks!
