### ISSUE TITLE
Unable to load SQLite.Interop.dll

### ISSUE THREAD

**Issue by parya-j** [ErikEJ/SqlCeToolbox#916]
A dll error shows up and the connections  won't show anything except for the error.
### Steps to reproduce
After installation, 30 files got extracted in the folder (instead of 48) and when opening this error shows up: " Unable to load SQLite.Interop.dll" under Data Connections

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon) 4.8.738.0

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)  SSMS 18.9.2

**Comment by ivan-kljajic** [comment]
I also have this issue. I worked around it by manually copying the DLL from the "src/GUI/SqlCe35Toolbox/x86" folder in the code repository into the extension's folder. (x86 since SQL Server Management Studio is a 32-bit application).
I did not fully test every function of the extension though to see if more than just that one missing DLL from the vsix file fixes everything.

**Comment by ErikEJ** [comment]
Should be fixed in latest daily build
