### ISSUE TITLE
New version crashes visual studio

### ISSUE THREAD

**Issue by Supermariocasti** [ErikEJ/SqlCeToolbox#940]
I can not access the SQL lite/compact server compact tool box. When I try to see the list of databases or create a connection Visual studio crashes and re-start. After VS restart there is an yellow message on top that says "Previous session terminated unexpectedly. Disable SQLite and SQL server Compact tool box 4.8.755 might help prevent similar issue" 

### Steps to reproduce
Just try to access one of my DBs or try to add a connection

### Further technical details)

Database engine: (SQlite, SQL Compact or SQL Server)
SQL compact edition version 4.0
Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual studio 2017 V15.9.38
>Net framwork 4.8

I try to enable the tool in SSMS version 18 but I did not work. Try to follow instructions but did not work

**Comment by ErikEJ** [comment]
Need to see some error messages or logs. Maybe your SQL Compact install is broken?

**Comment by erikbenton** [comment]
I am also experiencing issues after installing the extension where my Visual Studio 2022 becomes completely useless. VS cannot open any solutions without many error messages popping up and doesn't even recognize .cs files.

### What happens

I install the extension to view a database file.
I restart Visual Studio and ~10 error messages pop up.
After clicking through them all, it's very apparent VS did not load anything correctly (even Solution Explorer is not working).
Even trying to close VS, there's another error and I eventually have to kill the task in Task Manager.
Restarting VS just causes the same events to occur.

### Steps to reproduce

Open "Extensions" menu in VS 2022 to install an extension
Install "SQLite and SQL Server Compact Toolbox" extension
Close VS 2022 and let VSIX modify/install the extension
Reopen VS 2022 and open any solution.

### How to "reset"

Open VS Installer and "repair" installation.

### Further technical details

Windows 10
Visual Studio 2022 version 17.2.3

### Errors that pop-up upon opening

![sqlite_toolbox_extension_errors_1](https://user-images.githubusercontent.com/20894571/173138610-b6067a5c-81d2-4541-b0e2-50bc08f3bcd7.PNG)
![sqlite_toolbox_extension_errors_2](https://user-images.githubusercontent.com/20894571/173138611-8e723baa-2fac-4ca2-86e2-9302e55d4d1d.PNG)
![sqlite_toolbox_extension_errors_3](https://user-images.githubusercontent.com/20894571/173138613-06da2ce7-34f2-4c4d-82e5-cf55558eea1c.PNG)
![sqlite_toolbox_extension_errors_4](https://user-images.githubusercontent.com/20894571/173138614-3d797918-b624-4088-b70a-3f02cf8d9e88.PNG)
![sqlite_toolbox_extension_errors_5](https://user-images.githubusercontent.com/20894571/173138615-f613c63b-481c-4303-b5ae-e40dd075d439.PNG)

### What Solution Explorer looks like

![sqlite_toolbox_extension_everything_wonky_proof](https://user-images.githubusercontent.com/20894571/173138607-34577d0b-1229-4d22-9960-8b3d9d248701.PNG)

### What happens when I try to close

![sqlite_toolbox_extension_errors_try_to_close](https://user-images.githubusercontent.com/20894571/173138604-855887ff-c27d-4148-8876-6c3e58081453.PNG)

![sqlite_toolbox_extension_whats_running](https://user-images.githubusercontent.com/20894571/173138608-8080d083-37c3-4274-b217-d531026dda5b.PNG)

.

**Comment by ErikEJ** [comment]
That looks bad, sorry about that. And thanks for the info. Anything in activity log? Which exact VS version?

**Comment by ErikEJ** [comment]
I will try to revert the change I suspect causing this tomorrow in the latest daily.

**Comment by erikbenton** [comment]
No worries, and sorry for all of the pics, I thought it'd be easier than typing/describing.

Where can I find the activity logs?
I can do the install again (I've done this twice now thinking it might be an extension/environment conflict), repairing VS 2022 just takes a bit...

The VS version is:
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.3

**Comment by ErikEJ** [comment]
The activity log.xml file mentioned in the error messages...

**Comment by erikbenton** [comment]
Oh duh, sorry, was thinking the "Install log" that VSIX offers...

I can't find the exact file it mentions, but there's an ActivityLog.Setup.xml

![sqlite_toolbox_extension_activity_log](https://user-images.githubusercontent.com/20894571/173144893-fe3da91e-2d78-45b4-a8aa-df6c39781b9a.PNG)

**Comment by ErikEJ** [comment]
That does not really help...

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build (.756) - please try it out and let me know.

**Comment by erikbenton** [comment]
The daily build (.756) still did not work.

I downloaded it from the VSIX Gallery link in the README and installed it but the same list of events occurred when I reopened VS.

There's some ERROR info in the ActivityLog file this time, but GitHub won't let me upload XML.
How best can I share that with you?

I did save the VSIX install log just in case

[sqlite_tools_extensions_install_log_756.txt](https://github.com/ErikEJ/SqlCeToolbox/files/8882281/sqlite_tools_extensions_install_log_756.txt)

**Comment by ErikEJ** [comment]
Copy paste the actual error text?

**Comment by ErikEJ** [comment]
Or .zip the file??

**Comment by erikbenton** [comment]
I just changed it to txt file and had to remove some personal info...
[ActivityLog.txt](https://github.com/ErikEJ/SqlCeToolbox/files/8882377/ActivityLog.txt)

**Comment by erikbenton** [comment]
For what it is worth, I am able to install the extension on the same machine without problem for VS 2019 (specifically):
Microsoft Visual Studio Community 2019
Version 16.11.10

**Comment by ErikEJ** [comment]
I do not see any errors related to SQLite toolbox in that log file (in fact no serious errors at all)

Successfully loaded extension 'SQLite and SQL Server Compact Toolbox' (41521019-e4c7-480c-8ea8-fc4a2c6f50aa)...
          C:\USERS\ERIK BENTON\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\17.0_58ED0053\EXTENSIONS\UCYMC1YF.IA1\

**Comment by ErikEJ** [comment]
I suspect some other extension is interfering with SQLite Toolbox. Try installing in  another VS SKU or in Vs 2022 on another PC:

**Comment by erikbenton** [comment]
It's definitely this specific machine's install/extensions...

Short story: Apparently altering any extensions on my machine causes it to crash, not just the SqlCeToolbox, so I'm going to retry again on a completely fresh VS 2022 install (not just a "repair").

Long story below:
(This is all regarding the extension download offered via VS studio toolbar, not .756)

I installed the extension on another laptop with fresh VS 2022 install to see if it would work.
It did work, so I went and looked at the extensions to compare and see if there were any glaring differences between the 2 computers.
The not-working-machine had an "Experimental" Windows App Preview extension installed, so I uninstalled it and another.
As soon as I opened VS 2022 again, same errors and messages popped up as before and nothing worked/loaded.
And this was without the SqlCeToolbox extension installed at all.

So I'm going to install VS 2022 fresh again (not just repair) on the not-working-machine and hopefully it will become working-machine...

**Comment by ErikEJ** [comment]
Glad you are getting closer. 

Happy to have a look at an activitylog from a crash.

**Comment by erikbenton** [comment]
Again, no luck with my machine =(

Fresh VS 2022 install, only extensions shown on install were the 4 "standard" ones for the "Web Development" install option (Nuget Recommender, Intellisense, Windows Library Manager, SQL Server Data Tools).
Same errors and everything occured.

Here's the Activity Log:
[ActivityLog_AfterFreshInstall.txt](https://github.com/ErikEJ/SqlCeToolbox/files/8884242/ActivityLog_AfterFreshInstall.txt)

I need a little break from all of the install/repair screens for the day...

Thanks for the help and quick replies, I've appreciated it!

**Comment by Supermariocasti** [comment]
Hello
Is it posible roll back to the older working version?
Or where I can download it?

**Comment by ErikEJ** [comment]
You can try the latest daily where I made some changes. Also you can help me troubleshoot as requested earlier.

**Comment by erikbenton** [comment]
Quick update: Tried adding another extension unrelated to this at all (Add File) and it also crashed my install of VS 2022 in the same manner. I'm fairly certain it's something on Visual Studio/Microsoft's side (or I did something stupid installing VS?).

I had the "Add File" extension installed and working before all of this mess too, but it was installed on a version of VS that was later updated to the current VS 2022 Version 17.2.3.

@Supermariocasti If you're experiencing the same issues as me, I don't think this is caused by SqlCeToolbox but rather VS 2022 itself is having issues with extensions in general.

**Comment by ErikEJ** [comment]
@erikbenton @Supermariocasti Again - a activity log captured during a crash would be very helpful.

**Comment by ErikEJ** [comment]
@Supermariocasti Try the latest daily...

**Comment by ErikEJ** [comment]
Assume this is fixed, latest daily now published to MarketPlace - please open a new issue if not

**Comment by erikbenton** [comment]
Went through the process of installing the SqlCeToolbox extension again.

After installing, I looked at the VSIX Install Log and there were a few errors while trying to install, but apparently VSIX claimed it was "installed correctly" on the install panel (but not in its own install log? see note about VSIX install log).

Opened up VS 2022 and the same error messages and everything happened.

Again, pretty sure this is VS 2022 or VSIX and not this specific extension causing this to happen.

***Note VSIX Install Log**
Error for VSIX install on lines 179 -> 454
Eventually claims on line 455: "The extension with ID '41521019-e4c7-480c-8ea8-fc4a2c6f50aa' is not installed to Microsoft Visual Studio Community 2022."
Which is the ID of this extension listed on line 15
[VSIX_install_log.txt](https://github.com/ErikEJ/SqlCeToolbox/files/8910580/VSIX_install_log.txt)

[ActivityLog_Installing_SqlCeToolbox_again.txt](https://github.com/ErikEJ/SqlCeToolbox/files/8910581/ActivityLog_Installing_SqlCeToolbox_again.txt)

**Comment by ErikEJ** [comment]
I need the Activitylog from a crash. Not the install logs.

**Comment by erikbenton** [comment]
The activity log is right below the VSIX install log, but here it is again.
[ActivityLog_Installing_SqlCeToolbox_again.txt](https://github.com/ErikEJ/SqlCeToolbox/files/8911167/ActivityLog_Installing_SqlCeToolbox_again.txt)

And, for what it's worth, I just did everything again with the "updated" VS 2022 (Version 17.2.4 vs 17.2.3) and exactly the same things happened even down to the errors and install logs having all the same messages (minus the time stamps differing and VS version).

**Comment by ErikEJ** [comment]
Sorry. I will have a quick look. But it sounds like your machine is broken.

**Comment by Supermariocasti** [comment]
Typically where I can find that log?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErikEJ** [comment]
I the dialog the pops up during a crash there is a link. Did you try the latest build?

**Comment by Supermariocasti** [comment]
I try to install the newest version and I got this error message (look in
the picture)

**Comment by ErikEJ** [comment]
I can see any picture. Go to github and upload one, email does not work.

**Comment by Supermariocasti** [comment]
I just realized that enenthough I got the error during the installation.
The tool is working in vs 2017.
So I'm ok at this point
Thank you

**Comment by Supermariocasti** [comment]
The error message says
This extension can not be installed because the following references are missing: Visual studio MPF 14.0

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErikEJ** [comment]
@Supermariocasti Please create a new issue with exact error message and log texts

**Comment by ErikEJ** [comment]
You will see a dialog with a link to the file when VS crashes. Have you tried the latest build?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErikEJ** [comment]
@Supermariocasti  at least copy the text from the message box (or share a screen shot)
